### ISSUE TITLE
Add support for recalculate for insights that don't yet support it

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#565]
let's manage list of insights which are not support recalculation and split them into different issues.
please consult with @asafchen-dig before you start
please note that in the backend there is a property "IsRecalculateEnabled" which indicates if supported by insight.
basically, the client overrides it (manages it by itself) and has its own logic, don't change how the client behaves for now, @shaykeren  will do it later. just update it

- [x] https://github.com/digma-ai/digma-collector-backend/issues/843
- [ ] digma-ai/digma-intellij-plugin#593
- [x] digma-ai/digma-intellij-plugin#592
- [x] digma-ai/digma-collector-backend#1133
- [x] digma-ai/digma-collector-backend#1134
- [ ] digma-ai/digma-intellij-plugin#596
- [ ] digma-ai/digma-intellij-plugin#597
- [x] digma-ai/digma-intellij-plugin#598
- [ ] digma-ai/digma-intellij-plugin#599
- [ ] digma-ai/digma-intellij-plugin#600
- [ ] digma-ai/digma-intellij-plugin#601
- [x] digma-ai/digma-intellij-plugin#602

Should be converted to epic?

**Comment by borisermakof** [comment]
@shaykeren Maybe we should rename `Recalculate` label to something different on the UI because its counterintuitive. User will think that we will recalculate existing data in existing date range, but in fact we are changing the `start date` of period that we want to be calculated. Or at least to add Tooltip with explanation. This `Recalculation` could not be reverted if we click it

**Comment by shaykeren** [comment]
> 

@doppleware ?
